version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - sue445
    ignore:
      - dependency-name: "getsentry/action-release"
        versions:
          #  # c.f. https://github.com/getsentry/action-release/issues/258
          - "2"

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      timezone: Asia/Tokyo
      time: "05:00"
    open-pull-requests-limit: 99
    assignees:
      - sue445
    versioning-strategy: lockfile-only
